Repository openshift/openstack-test, pull requests merged in 2023-10, with the labels that each got.

#104 OCPBUGS-13781: Don't assert identical server groups in multi-AZ
  test/extended/openstack/servergroup.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#127 refactor: Add convenient machine listing
  test/extended/openstack/bz_2022627.go
  test/extended/openstack/machine.go
  test/extended/openstack/machines/list.go
  test/extended/openstack/machineset.go
Labels: lgtm, approved

#126 OSASINFRA-3278: add tests when etcd runs on additional local disk
  test/extended/openstack/local-bd-etcd.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: lgtm, approved, jira/valid-reference

#124 Verify machines attributes conform to CPMS
  test/extended/openstack/cpms.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: lgtm, approved

#128 local-bd-etcd: fix CPMS
  test/extended/openstack/cpms.go
  test/extended/openstack/local-bd-etcd.go
Labels: lgtm, approved
