Repository openshift/openstack-test, pull requests merged in 2023-02, with the labels that each got.

#72 Parameterize the Load Balancer service creation timeout
  test/extended/openstack/loadbalancers.go
Labels: lgtm, approved

#82 Bug OCPBUGS-7105: Fix MachineSet test
  test/extended/openstack/machinesets.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/valid-reference

#84 OCPBUGS-7310: Do not consider deleted instance as error
  test/extended/openstack/servers.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/valid-reference

#83 OSASINFRA-3088: Restore gophercloud/utils to the previous version
  go.mod
  go.sum
  vendor/github.com/gophercloud/utils/gnocchi/client.go
  vendor/github.com/gophercloud/utils/gnocchi/results.go
  vendor/github.com/gophercloud/utils/internal/pkg.go
  vendor/github.com/gophercloud/utils/internal/util.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/doc.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/results.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/utils.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#88 OCPBUGS-7310: Fix test checking if Machine addresses match VMs
  test/extended/openstack/servers.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/valid-reference

#91 OSASINFRA-3108: Bump gophercloud/utils
  go.mod
  go.sum
  vendor/github.com/gophercloud/utils/gnocchi/client.go
  vendor/github.com/gophercloud/utils/gnocchi/results.go
  vendor/github.com/gophercloud/utils/internal/pkg.go
  vendor/github.com/gophercloud/utils/internal/util.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/doc.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/results.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/utils.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#93 OSASINFRA-3079: Disable LB tests in proxy envs
  test/extended/openstack/loadbalancers.go
Labels: lgtm, approved, jira/valid-reference
