Repository openshift/openstack-test, pull requests merged in 2024-07, with the labels that each got.

#177 OSASINFRA-3402: Use Gophercloud v2.0.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#178 OCPBUGS-35064: Fetch a cluster external network for egress ip
  test/extended/openstack/egressip.go
  test/extended/openstack/loadbalancers.go
  test/extended/openstack/utils.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#181 Add skip for server group tests
  test/extended/openstack/servergroup.go
Labels: lgtm, approved
