Repository openshift/openstack-test, pull requests merged in 2025-06, with the labels that each got.

#239 make: Check for updates in cmd before building
  Makefile
Labels: lgtm, approved

#240 Don't include infra nodes in worker node list
  test/extended/openstack/servergroup.go
Labels: lgtm, approved

#236 OCPBUGS-55931: Fix noAllowedAddressPairs test
  test/extended/openstack/machines/machines.go
  test/extended/openstack/ocpbug_1765.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#247 NO-JIRA: trivial: Add missing error check'
  test/extended/openstack/bz_2073398.go
Labels: lgtm, approved, jira/valid-reference
